export const TAROT_CARDS = [
  // 22 Lá Ẩn Chính (Major Arcana)
  { name: "The Fool", mean: "Khởi đầu mới, ngây thơ, mạo hiểm" },
  { name: "The Magician", mean: "Tập trung, ý chí, sự sáng tạo" },
  { name: "The High Priestess", mean: "Trực giác, tri thức thần bí" },
  { name: "The Empress", mean: "Sự sung túc, thiên nhiên, màu mỡ" },
  { name: "The Emperor", mean: "Quyền lực, cấu trúc, kỷ luật" },
  { name: "The Hierophant", mean: "Truyền thống, niềm tin, giáo dục" },
  { name: "The Lovers", mean: "Tình yêu, hòa hợp, lựa chọn" },
  { name: "The Chariot", mean: "Chiến thắng, sự kiểm soát, quyết tâm" },
  { name: "Strength", mean: "Sức mạnh nội tâm, lòng can đảm" },
  { name: "The Hermit", mean: "Sự tĩnh lặng, tìm kiếm sự thật" },
  { name: "Wheel of Fortune", mean: "Số phận, bước ngoặt, chu kỳ" },
  { name: "Justice", mean: "Công bằng, sự thật, luật pháp" },
  { name: "The Hanged Man", mean: "Sự hy sinh, góc nhìn mới" },
  { name: "Death", mean: "Sự kết thúc, chuyển đổi, tái sinh" },
  { name: "Temperance", mean: "Sự cân bằng, kiên nhẫn, điều độ" },
  { name: "The Devil", mean: "Sự ràng buộc, cám dỗ, vật chất" },
  { name: "The Tower", mean: "Sụp đổ đột ngột, thay đổi căn bản" },
  { name: "The Star", mean: "Hy vọng, niềm tin, phục hồi" },
  { name: "The Moon", mean: "Ảo tưởng, nỗi sợ, trực giác" },
  { name: "The Sun", mean: "Thành công, hạnh phúc, rạng rỡ" },
  { name: "Judgement", mean: "Sự thức tỉnh, đánh giá, tha thứ" },
  { name: "The World", mean: "Hoàn thành, viên mãn, du hành" },

  // 56 Lá Ẩn Phụ (Minor Arcana)
  // Bộ Gậy (Wands) - Đại diện cho năng lượng, hành động
  { name: "Ace of Wands", mean: "Cảm hứng mới, tiềm năng" },
  { name: "Two of Wands", mean: "Lên kế hoạch, quyết định" },
  { name: "Three of Wands", mean: "Mở rộng, chờ đợi kết quả" },
  { name: "Four of Wands", mean: "Ăn mừng, sự ổn định" },
  { name: "Five of Wands", mean: "Cạnh tranh, xung đột" },
  { name: "Six of Wands", mean: "Sự công nhận, chiến thắng" },
  { name: "Seven of Wands", mean: "Phòng thủ, kiên trì" },
  { name: "Eight of Wands", mean: "Tốc độ, thông điệp" },
  { name: "Nine of Wands", mean: "Bảo vệ thành quả, mệt mỏi" },
  { name: "Ten of Wands", mean: "Gánh nặng, trách nhiệm" },
  { name: "Page of Wands", mean: "Tin tức mới, sự khám phá" },
  { name: "Knight of Wands", mean: "Hành động nhanh, nhiệt huyết" },
  { name: "Queen of Wands", mean: "Tự tin, quyến rũ" },
  { name: "King of Wands", mean: "Lãnh đạo, tầm nhìn" },

  // Bộ Ly (Cups) - Đại diện cho cảm xúc, tình cảm
  { name: "Ace of Cups", mean: "Tình yêu mới, tràn đầy cảm xúc" },
  { name: "Two of Cups", mean: "Kết nối, đối tác" },
  { name: "Three of Cups", mean: "Tình bạn, hội họp" },
  { name: "Four of Cups", mean: "Sự thờ ơ, bỏ lỡ cơ hội" },
  { name: "Five of Cups", mean: "Nuối tiếc, nỗi buồn" },
  { name: "Six of Cups", mean: "Kỷ niệm, sự hồn nhiên" },
  { name: "Seven of Cups", mean: "Lựa chọn, ảo tưởng" },
  { name: "Eight of Cups", mean: "Rời đi, tìm kiếm ý nghĩa" },
  { name: "Nine of Cups", mean: "Sự mãn nguyện, ước mơ" },
  { name: "Ten of Cups", mean: "Gia đình hạnh phúc" },
  { name: "Page of Cups", mean: "Linh tính, tin vui tình cảm" },
  { name: "Knight of Cups", mean: "Sự lãng mạn, lời mời" },
  { name: "Queen of Cups", mean: "Thấu cảm, trực giác" },
  { name: "King of Cups", mean: "Cân bằng cảm xúc" },

  // Bộ Kiếm (Swords) - Đại diện cho trí tuệ, lý trí
  { name: "Ace of Swords", mean: "Sự thấu suốt, đột phá" },
  { name: "Two of Swords", mean: "Bế tắc, lựa chọn khó khăn" },
  { name: "Three of Swords", mean: "Đau lòng, tổn thương" },
  { name: "Four of Swords", mean: "Nghỉ ngơi, hồi phục" },
  { name: "Five of Swords", mean: "Thắng lợi cay đắng, tư lợi" },
  { name: "Six of Swords", mean: "Vượt qua khó khăn" },
  { name: "Seven of Swords", mean: "Sự lừa dối, bí mật" },
  { name: "Eight of Swords", mean: "Bị kìm kẹp, tự giới hạn" },
  { name: "Nine of Swords", mean: "Lo âu, mất ngủ" },
  { name: "Ten of Swords", mean: "Phản bội, sự kết thúc đau đớn" },
  { name: "Page of Swords", mean: "Sự tò mò, cảnh giác" },
  { name: "Knight of Swords", mean: "Xông xáo, vội vã" },
  { name: "Queen of Swords", mean: "Độc lập, sắc bén" },
  { name: "King of Swords", mean: "Công bằng, lý trí" },

  // Bộ Tiền (Pentacles) - Đại diện cho vật chất, công việc
  { name: "Ace of Pentacles", mean: "Cơ hội tài chính, thực tế" },
  { name: "Two of Pentacles", mean: "Sự cân bằng, linh hoạt" },
  { name: "Three of Pentacles", mean: "Hợp tác, kỹ năng" },
  { name: "Four of Pentacles", mean: "Sở hữu, sự an toàn" },
  { name: "Five of Pentacles", mean: "Khó khăn, mất mát tài chính" },
  { name: "Six of Pentacles", mean: "Sự rộng lượng, chia sẻ" },
  { name: "Seven of Pentacles", mean: "Kiên nhẫn, chờ đợi thu hoạch" },
  { name: "Eight of Pentacles", mean: "Sự chăm chỉ, thành thạo" },
  { name: "Nine of Pentacles", mean: "Độc lập, sang trọng" },
  { name: "Ten of Pentacles", mean: "Di sản, sự giàu có vững bền" },
  { name: "Page of Pentacles", mean: "Khởi đầu công việc, học hỏi" },
  { name: "Knight of Pentacles", mean: "Kiên định, tỉ mỉ" },
  { name: "Queen of Pentacles", mean: "Nuôi dưỡng, thực tế" },
  { name: "King of Pentacles", mean: "Thành đạt, thịnh vượng" }
];